### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by rombat** [conceptualspace/shuffle-for-plex#3]
Hi
It doesn't seem to be working anymore, I can't see the dice icon.
I'm using Firefox 77 and Plex web is version 4.30.2

**Comment by conceptualspace** [comment]
hmm, it's working for me on latest Plex, v4.35.1

can you upgrade and see if it makes a difference? also confirm if you are using a private window that the extension has permission to run

**Comment by rombat** [comment]
It seems that I've the latest version of Plex Media Server.
But I've figured out why it didn't work; I was accessing Plex through its IP http://127.0.0.1:32400/web/ and not through https://app.plex.tv/desktop
With this url it's working fine.

**Comment by conceptualspace** [comment]
👍

hopefully will have localhost support soon too (issue #1)
